language: java
# We need to keep using this dist to make oraclejdk8 installation work.
# https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/9
dist: trusty
jdk:
  - oraclejdk8
  - openjdk11
# https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c0fddd6d7622_key -iv $encrypted_c0fddd6d7622_iv -in scripts/.travis.key.gpg.enc -out $HOME/.travis.key.gpg -d
  - chmod 600 $HOME/.travis.key.gpg
  # $HOME/.gradle/gradle.properties contains following properties
  #
  # signing.keyId=****
  # signing.secretKeyRingFile=/home/travis/.travis.key.gpg
  # signing.password=****
  # sonatypeUsername=****
  # sonatypePassword=****
  - openssl aes-256-cbc -K $encrypted_7b9d62f05c7d_key -iv $encrypted_7b9d62f05c7d_iv -in scripts/user_gradle.properties.enc -out $HOME/.gradle/gradle.properties -d
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/publish.sh
  on:
    tags: true
    branch: master
    jdk: 'oraclejdk8'
env:
  global:
    - secure: "du2+jUVzjd5kqcq0OLF9skDexBwYVkqmnQGiCWxgiDS5tf1jJO7vOWW3GnZulzJgr0EsZnGkX9cDhD2d8heLdpSuVjgXUmHH/0TzBdd8EdMBKrv+xkYLs0hEnAzHh55jbURXOHmi6rbqqdBWqxp7rylMC6MCMqD3JECLQkTIkiwiV0Ymg3UXLT9qUU+hIgoSio0UOxfkNiqMYGZuUAFgHCgIek+bKKavQmIenoBMzcLr+Nq/7UqgEN9tlZ2CAIq8zDe4tiO/HAQ+k2QapZubGnMq9WO7dz7HE342RwKBCC+bYl4iV7/oUEO8zdaSwQjvVTxRY5FIyNJDjxLi/jlhIasKWNzscHkqETDxou/wiLwZCCjrSBqt4GvdN9oo+jsfMJ2nBiu7CTdkpUiU6kK12of60OFLQVDyKK3PhiOoJi90bygBMvggtGiQGqnl86ETmylhOsJShpBMxtFnOTWztUcOhU93E0AnixSeBNqfl8exCGocbOJkggkTILo9ineqZdFhsl6QrkPDXqkd++g2SudO8+fcr2/F6K987QYueNeMzJVOdI3a9bUQ0PDogVRi1tbQH7lH+jHYKLZtt2mm8jBWx1YiDwo/Wqe4XVEHk1qPagfnZEdXjn7nM+RLUcYkSQ1KHnasyOye1sgkO32e2yiVMv9eXjyGFCnvemQEL/w="
