= Tracing
:base_version: 6.0.0
:modules: brave,processor

Decaton can integrate with distributed tracing frameworks so that you can associate the processing of a message
with the component that originally sent that message. This is implemented via the
link:../processor/src/main/java/com/linecorp/decaton/processor/tracing/TracingProvider.java[TracingProvider]
interface. Note that you will generally also need a custom KafkaProducerSupplier that records trace information
(e.g. in a Kafka header), both in the component that produces original messages and in any RetryConfig that
you are using.

Currently the only implementation is BraveTracingProvider, which integrates with
link:https://github.com/openzipkin/brave[OpenZipkin Brave]. It should be combined with a KafkaProducerSupplier
that supplies a link:https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-clients/README.md#setup[TracingProducer]

== Example

[source,java]
.TracingMain.java
----
...
SubscriptionBuilder.newBuilder("tracing-key-processor")
                   .enableTracing(
                           new BraveTracingProvider())
...
---
